#!/usr/bin/env bash
set -euo pipefail

# Optional: pass --draft to open a draft PR
IS_DRAFT="${1:-}"

# --- Requirements ---
command -v git >/dev/null 2>&1 || { echo "git not found"; exit 1; }
command -v gh  >/dev/null 2>&1 || { echo "GitHub CLI (gh) not found. Install from https://cli.github.com/"; exit 1; }
gh auth status >/dev/null || { echo "You must be authenticated with 'gh auth login'."; exit 1; }

# --- Determine branches ---
BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# Determine base branch logic
if [[ "$BRANCH" == "canary" ]]; then
  BASE="main"
  if ! git show-ref --verify --quiet refs/heads/main; then
    echo "Error: 'main' branch does not exist in this repository. Cannot create PR from canary."
    exit 1
  fi
else
  BASE="canary"
  if ! git show-ref --verify --quiet refs/heads/canary; then
    echo "Error: 'canary' branch does not exist in this repository. Cannot create PR."
    exit 1
  fi
fi

# --- Push branch upstream (if needed) ---
# This will set upstream if none exists; otherwise it's a no-op push
git push -u origin "$BRANCH"

# --- PR content ---
DATE_UTC="$(date -u +"%Y-%m-%d %H:%M:%SZ")"
BODY=$'⚠️ **Autogenerated PR**\n\nThis pull request was created automatically from branch '"\`$BRANCH\` on $DATE_UTC."$'\n\n- Please verify the base branch, reviewers, and labels.\n- Edit this description as needed before merging.\n'

# --- Draft flag handling ---
DRAFT_FLAG=""
if [[ "$IS_DRAFT" == "--draft" || "${DRAFT:-}" == "1" ]]; then
  DRAFT_FLAG="--draft"
fi

# --- Create or open PR ---
# If an open non-draft PR already exists for this branch, open it and exit.
OPEN_NON_DRAFT_COUNT="$(gh pr list --head "$BRANCH" --state open --json isDraft,number -q '[.[] | select(.isDraft==false)] | length' 2>/dev/null || echo 0)"

if [[ "${OPEN_NON_DRAFT_COUNT}" -gt 0 ]]; then
  echo "An open PR already exists for '$BRANCH'. Opening it…"
  gh pr view --web
  exit 0
fi

# If there is an open draft PR
OPEN_DRAFT_COUNT="$(gh pr list --head "$BRANCH" --state open --json isDraft,number -q '[.[] | select(.isDraft==true)] | length' 2>/dev/null || echo 0)"
if [[ "${OPEN_DRAFT_COUNT}" -gt 0 ]]; then
  if [[ -z "${DRAFT_FLAG}" ]]; then
    echo "A draft PR exists for '$BRANCH'. Marking it ready for review…"
    gh pr ready
  else
    echo "A draft PR exists for '$BRANCH'. Opening it…"
  fi
  gh pr view --web
  exit 0
fi

# No open PRs (regardless of closed ones) — create a new one
gh pr create --title "$BRANCH" --body "$BODY" --base "$BASE" $DRAFT_FLAG
echo "PR created from '$BRANCH' → base '$BASE'."